ALTER TABLE resultados
  ADD COLUMN pole_sprint TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN ganador_sprint TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN pole_final TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN ganador_final TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN campeon TINYINT(1) NOT NULL DEFAULT 0;
